spring:
  devtools:
    restart:
      exclude: init/**    #파일 변경을 감지하여 무한 리부팅이 발생 함
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      org.hibernate.envers.audit_table_suffix: _HIS
      org.hibernate.envers.modified_flag_suffix: _CHANGED
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
      hibernate.jdbc.batch_size: 100
      hibernate.jdbc.order_inserts: true
      hibernate.query.in_clause_parameter_padding: true
    open-in-view: false
  messages:
    basename: messages/message
  servlet:
    multipart:
      max-file-size: 3MB
      enabled: true
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          no-store: true
          no-cache: true
debug: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework: INFO
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
server:
  port: 9999
management:
  endpoints:
    web:
      exposure:
        include: ["health", "loggers"]
  health:
    defaults:
      enabled: false

---
app:
  constants:
    domain:
      url: http://localhost:${server.port}